### PR TITLE
ConfigEtcd is a subclass of Config

### PR DESCRIPTION
**Pull request by tomruttle**
I don't think there's anyone in TES using etcd yet, but this is potentially a breaking change if anyone outside the organisation is using it.

(Sorry about linting @cressie176. I've used the file from refdata and haven't enforced it anywhere.)

### CODE REVIEW

**Comment by dmorgantini** [comment]
@tomruttle please action or close this pr

**Comment by tomruttle** [comment]
@cressie176 Some clean-up of the git history in this branch still required, but are you happy for this to be merged?

**Comment by cressie176** [comment]
Think it needs testing. The service I care about is [service-jobs-http2amqp](https://github.com/tes/service-jobs-http2amqp). This watches a key in etcd and uses it to [trigger a hot reload](https://github.com/tes/service-jobs-http2amqp/blob/master/cluster.js#L16). We use this to update a cache of json schemas without downtime.

However...

The schemas are used to validate salesforce / jobs messages. They don't change very often and it's not a big deal to restart the service out of hours. In principle it's a good idea, and I was hoping to start using it for live config changes too. That never happened.

I'm also not sure if it still works - I didn't see the service auto reload the last time we tried to use it.

Given these two points I could live with binning the hot reload feature, if it proves a pain to carry over.

To test...

The approach I've used with Rascal / electric-rascal is to manually publish a beta version to sinopia by changing the version number to 0.N+1.0-beta (where N is the current minor version in package.json)

I then update one service to depend on the beta version and test / observe over a few days. To test http2amqp you could update package.json as describe above then deploy to development. Tail the logs and run http://jenkins-native.tescloud.com/job/tools-jobs-reload/ to trigger the reload

**Comment by cressie176** [comment]
```
2016-04-12T08:27:57.161Z - warn: Reloading cluster
2016-04-12T08:27:58.877Z - info: Started http2amqp
2016-04-12T08:27:58.879Z - info: Jobs http2amqp worker 3 is listening on 0.0.0.0:5000
2016-04-12T08:27:59.258Z - info: Started http2amqp
2016-04-12T08:27:59.260Z - info: Jobs http2amqp worker 4 is listening on 0.0.0.0:5000
2016-04-12T08:27:59.262Z - warn: Jobs http2amqp worker 1 has disconnected
2016-04-12T08:27:59.263Z - warn: Jobs http2amqp worker 2 has disconnected
2016-04-12T08:28:09.264Z - info: Workers appears stable. Reseting retry count
```
Just tested with existing module-tsl-cluster and hot reload works.

**Comment by MerlinDMC** [comment]
Reopen if you still want to work on this.
node-etcd also doesn't seem to support the v3 endpoints and v2 is in the process of being removed from etcd.

**Pull request closed without merging**
