### PR TITLE
Remove vulnerable istanbul and migrate to nyc

### PR DESCRIPTION
**Pull request by rouanw**
The version of `istanbul` being used is vulnerable:

```
───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ istanbul [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ istanbul > handlebars                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/755                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

This pull request migrates the coverage tooling to use [nyc](https://github.com/istanbuljs/nyc) instead.

### CODE REVIEW

**Comment by BorePlusPlus** [comment]
I have 2 questions...

I wonder if we should add `mocha.opts` with `--recursive` (seeing that cli arg was dropped). Not needed at the moment, but prevent surprise in the future.

What's our strategy regarding `package-lock.json` in modules. I can see that it can bring value by bringing consistency between developers of the module, but once module is being used as a dependency it gets ignored. Should we keep it in repo or .gitignore it? Do you have an opinion on that?

**Comment by rouanw** [comment]
> I wonder if we should add mocha.opts with --recursive (seeing that cli arg was dropped). Not needed at the moment, but prevent surprise in the future.

I think `mocha` has some sensible defaults. E.g. I was planning on renaming the `tests` directory to `test` so we don't have to specify it, but didn't want to do that while https://github.com/tes/conflab/pull/19 was open. I'll do some testing on what we need for recursive directory traversal (I'm hoping nothing).

> What's our strategy regarding package-lock.json in modules. I can see that it can bring value by bringing consistency between developers of the module, but once module is being used as a dependency it gets ignored. Should we keep it in repo or .gitignore it? Do you have an opinion on that?

I see no reason not to commit it. It does help with consistency and is likely to show us if contributors are using wildly different node or npm versions.

From the [npm docs](https://docs.npmjs.com/files/package-locks):

> Using a locked package is no different than using any package without a package lock

^^ I think this means you're right that it makes no difference to consumers of the library.

> It is highly recommended you commit the generated package lock to source control: this will allow anyone else on your team, your deployments, your CI/continuous integration, and anyone else who runs npm install in your package source to get the exact same dependency tree that you were developing on. Additionally, the diffs from these changes are human-readable and will inform you of any changes npm has made to your node_modules, so you can notice if any transitive dependencies were updated, hoisted, etc.

^^ Means committing is the "done thing" for whatever that's worth.

**Comment by rouanw** [comment]
Just checked the [mocha docs](https://mochajs.org/#the-test-directory) and we will need the `--recursive` flag. Let's leave this PR open. I've rebased on master and will add some further changes.

**Comment by BorePlusPlus** [comment]
> we will need the `--recursive` flag

When you say that, do you mean in the future when you add more tests? At the moment all the tests are in `tests` directory, subdirectories are only used to hold data files. 
But I think having recursive flag set is what most developers (at least that I work with) would expect.

**Comment by rouanw** [comment]
@BorePlusPlus I just mean I agree it's a good idea to add it and that it seems to fit with this PR 😄 Thanks for spotting!

I've updated the PR to:
- set the `--recursive` flag
- move the tests from `tests` to `test` so we don't need to tell mocha where do find them
- update `jshint` and configure `jshint` to be `mocha`-aware
- turns out we were ignoring our tests when linting, so I removed that behaviour and fixed a few  issues in the tests
- added a `pre-push` hook to run `npm audit`
- increased the code coverage threshold from 80% to 90% seeing that we're already there

**Comment by BorePlusPlus** [comment]
Looks good to me. :+1:

**Pull request merged**
